# Generated by Django 2.2.7 on 2020-01-10 19:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_title', models.CharField(db_index=True, max_length=200)),
                ('location', models.CharField(db_index=True, max_length=200)),
                ('hiring_date', models.DateField(default=django.utils.timezone.now)),
                ('budget', models.PositiveIntegerField()),
                ('year_of_experience', models.PositiveIntegerField()),
                ('hiring_manager', models.CharField(default='None', max_length=200)),
                ('status', models.CharField(choices=[('Z', 'To be start'), ('A', 'On going'), ('B', 'Offer'), ('C', 'Filled'), ('D', 'Stand-by'), ('E', 'Cancelled')], default='To be start', max_length=2)),
            ],
            options={
                'verbose_name': 'position',
                'verbose_name_plural': 'Manage Positions',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='CV')),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='UPLOADED AT')),
                ('l', models.TextField(default='None', max_length=20000, verbose_name='Raw Text')),
                ('author', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Document', to=settings.AUTH_USER_MODEL, verbose_name='USER')),
            ],
            options={
                'verbose_name': 'CV',
                'verbose_name_plural': 'Upload candidates from CV',
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField()),
                ('ral', models.PositiveIntegerField()),
                ('education', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=200, validators=[django.core.validators.EmailValidator(message='invalid email')])),
                ('url', models.CharField(max_length=200, null=True)),
                ('tag', models.CharField(max_length=200)),
                ('importedFrom', models.CharField(default='CV', max_length=200, verbose_name='Imported from')),
                ('rawText', models.CharField(max_length=200000000000, null=True)),
                ('experiences', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('Z', 'Prospect'), ('A', 'To Call'), ('B', 'Recall'), ('C', 'Not Interested'), ('D', 'Waiting feedback'), ('E', '1° interview'), ('F', '2° interview'), ('G', 'Lack of hard skills'), ('H', 'Lack of soft skills'), ('I', 'Retired'), ('L', 'Under Offer'), ('M', 'Refuse Offer'), ('N', 'Filled')], default='Prospect', max_length=2)),
                ('note', models.TextField(default='None about this candidate', max_length=200)),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='Candidate', to=settings.AUTH_USER_MODEL, verbose_name='USER')),
                ('cv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cv', to='handling.Document')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Position', to='handling.Position')),
            ],
            options={
                'verbose_name_plural': ' Manage Candidates',
                'ordering': ['name'],
                'unique_together': {('email', 'name')},
            },
        ),
    ]
